### ISSUE TITLE
几种实现垂直居中的方法

### ISSUE THREAD

**Issue by innerWang** [innerWang/blogs#7]

**Comment by innerWang** [comment]
1： 使用flex
```html
<div class="parent">
   <div class="child"></div>
</div>
```

```css
.parent{
  border: 1px solid red;
  height: 300px;
  
  display: flex;
  justify-content: center;
  align-items: center;
}

.child {
  border: 1px solid green;
  width: 50px;
  height: 50px;
}
```

**Comment by innerWang** [comment]
2. 使用 绝对定位 和 transform

```html
<div class="parent">
   <div class="child"></div>
</div>
```

```css
.parent{
  border: 1px solid red;
  height: 300px;
  
  position:relative;
}

.child {
  border: 1px solid green;
  height: 50px;
  width:50px;
  
  position: absolute;
  top: 50%;
  left: 50%;
  transform:translate(-50%,-50%);
}
```

**Comment by innerWang** [comment]
3. 使用 绝对定位 和 margin:auto
```html
<div class="parent">
   <div class="child"></div>
</div>
```

```css
.parent{
  border: 1px solid red;
  height: 300px;
  
  position:relative;
}

.child {
  border: 1px solid green;
  height: 50px;
  width:50px;
  
  position: absolute;
  top: 0;     // 只需要`top = bottom`    +` margin:auto` 则可实现垂直居中
  left: 0;      // 只需要`left = right`    +` margin:auto` 则可实现水平居中
  right:0;
  bottom:0;
  margin:auto;
}
```

**Comment by innerWang** [comment]
4. 使用 绝对定位和 margin-top margin-left
```html
<div class="parent">
   <div class="child"></div>
</div>
```

```css
.parent{
  border: 1px solid red;
  height: 300px;
  
  position:relative;
}

.child {
  border: 1px solid green;
  height: 50px;
  width:50px;
  
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top:-25px;    //此处若使用百分比，是指父元素尺寸的百分比
  margin-left:-25px;
}
```

**Comment by innerWang** [comment]
5. 使用 ::after / ::before + vertical-align+ display:inline-block
```html
<div class="parent">
   <div class="child"></div>
</div>
```
```css
.parent{
  border: 1px solid red;
  height: 300px;
  
  text-align:center;
}

.child {
  border: 1px solid green;
  height: 50px;
  width:50px;
  
  display: inline-block;
  vertical-align: middle;
}

.parent::after{
  display:inline-block;
  content:'';
  height:100%;
  vertical-align: middle;
}
```

**Comment by innerWang** [comment]
6: 使用table标签
```html
<table class="parent">
   <tr>
     <td class="child">aaaaaaaaaa</td>
     <td class="child">aaaaaaaaaa</td>
   </tr>
</table>
```
```css
.parent{
  border: 1px solid red;
  height: 300px;
}

.child {
  border: 1px solid green;
}
```

**Comment by innerWang** [comment]
7. 使用 display: table   table-cell 和 vertical-align
```html
<div class="parent">
   <div class="child">aaaaaaaaaa</td>
</div>
```
```css
.parent{
  border: 1px solid red;
  height: 300px;
  
  display:table;
}

.child{
  border: 1px solid blue;
  
  display:table-cell;
  vertical-align: middle;
}
```
