### ISSUE TITLE
flex布局如何使用，常用属性有哪些？

### ISSUE THREAD

**Issue by innerWang** [innerWang/blogs#9]
块级布局侧重垂直方向、行内布局侧重水平方向，flex布局则与方向无关，可实现空间自动分配，自动对齐。

#### 1. flex相关基本概念
* 主轴(main axis)，主起点(main start)，主终点(main end)
* 侧轴(cross axis)，侧起点(cross start)，侧终点(cross end)

父元素的div在主轴上的尺寸叫做main size(主尺寸)，在侧轴上的尺寸叫做cross size(侧尺寸)。
所有的子元素叫做`flex item`，父元素叫做`flex container`

#### 2. 父元素 flex container 的六个属性
|属性|含义|
|:-|:-|
| flex-direction| 主轴方向 ，可选`row` ， `row-reverse`， `column` ， `column-reverse`|
| flex-wrap| 换行 ，可选`nowrap` ， `wrap` ， `wrap-reverse`|
| flex-flow| 上面两个的简写|
| justify-content| 主轴方向对齐方式|
| align-items| 侧轴对齐方式，默认是stretch， 决定元素整体在容器的什么位置|
| align-content| 多行/列内容对齐方式(用得较少)，决定行之间的间隔，只有一行时没有效果|

#### 3. 子元素 flex item 的六个属性
|属性|含义|
|:-|:-|
| flex-grow| 增长比例 (空间过多时),用于分配多余的空间，初始值0|
| flex-shrink | 收缩比例 (空间不够时)，初始值1|
| flex-basis|默认大小(一般不用)，初始值 auto|
| flex |上面三个的缩写|
| order |顺序(代替双飞翼)，可以改变子元素的顺序|
| align-self|自身的对齐方式|

**Comment by innerWang** [comment]
补充： 如何实现布局，使得空隙位于第一个和第二个子元素之间
```html
<div class="parent">
    <div class="child">1</div>
    <div class="child">2</div>
    <div class="child">3</div>
  </div>
```
```css
.child{
  border: 1px solid red;
}

.parent{
  border: 1px solid green;
  display: flex;
  justify-content: space-betweent;
}

.child:nth-child(2){
  margin-left:auto;
}
```
